name: "LaivyNPC"
version: ${project.version}
main: com.laivynpc.core.LaivyNPC
author: "ItsLaivy (@itslaivy)"
api-version: 1.13

load: POSTWORLD

website: "https://www.spigotmc.org/resources/110246/"

commands:
  laivynpc:
    aliases:
      - npc
    description: "General plug-in's command"

permissions:
  laivynpc.user.*:
    description: "General plug-in's users permissions"
    default: not op
  laivynpc.admin.*:
    description: "General plug-in's admin permissions"
    default: op